language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- black --check setup.py test rpi_dht22_exporter
- flake8 setup.py test rpi_dht22_exporter
- pytest test
- mypy test rpi_dht22_exporter
deploy:
  provider: pypi
  user: __token__
  distributions: sdist
  on:
    tags: true
    repo: urbas/rpi-dht22-exporter
    python: '3.8'
  password:
    secure: QjRiaO9Xak3RE9LmMPFR8iQCBCUfvJqoFWCBSUU2ZVyt6asp7rizt6v4z9XXqu1MNa43xvZ5AqOeIWDAu1qLzq1nyEfxtJ2SuHzjcv6GqfjNuvFEm4orM5p7BlwP+w0FfAxqiSrWft9qvjLOVULHI+yV/5iG9Qw+nAMElCM6VV+FLCl/bwNz6t2S4+8gnobC47JvzbNLgGUobjUbl2/ZjwTj2X5NmVOVFkj5a6ELtlJbInZeRvOT4TQ37csDomVJc4oizaNAq9Y6vsm4I/hjAWWXoSpREOnDlldmzmORFEr55SWNZIZehnHqkQKNd4/iBpJlURC2418iQwCZTP0pbuTS24eja+df8CPD9DIfiOlMIYlZlFpNA45ICFPqwMaPM10YRVl65PjZVabsHxgLo+vxRkqDjQeUupYh7O4pewQdJgUqZhAHEUWkrzV9jEjHcQWRmyhK4OlzffpiwIT1bAcmqlmc2IwnvQEFskQY0ua5Vav5iG+XEbfkZG5QBwnXfwpFbYn83JoQEHp9ppkEuS4+tJIF3ucMAz1bhMsPo98JRkV44YLeKP3Vcz796ObO1U18A4Pgf9nx9jgEZWPGrcMA11hesyNNl42SA8z/LhOUeFvGovpIhecGTavhRHIrZVT+YG6wCcqdn5bIHqLFqMSf9wKKo0EsF2s8f2IGtJk=
